---
# https://github.com/feng2208/spotify-helper

# mappings:
# - hosts:
#     - example.com
#     - "*.example.com" # 所有子域名
#   sni: sni.example.com
#   address: 100.1.1.1:443
# sni 和 hosts 都会用来验证服务器证书，如果 sni 以下划线开头(如：_example.com)，则 sni 不会被发送。


# https://apresolve.spotify.com/
spotify_ap:
  - ap-gue1.spotify.com
  - ap-guc3.spotify.com
  - ap-gew1.spotify.com
  - ap-gew4.spotify.com
  - ap-gae2.spotify.com
spotify_ap_address: 217.142.251.150:443


mappings:

### spotify
- hosts:
    - www.google.com
  sni: www.recaptcha.net
  address: 47.113.110.152:443

- hosts:
    - accounts.spotify.com
    - www.spotify.com
    - spclient.wg.spotify.com
  address: 217.142.251.150:443

- hosts:
    - login5.spotify.com 
    - apresolve.spotify.com 
    - api-partner.spotify.com
    - challenge.spotify.com
    - clienttoken.spotify.com
    - api.spotify.com
    - spotify.com
    - exp.wg.spotify.com
    - auth-callback.spotify.com
  address: 35.186.224.31:443
